INSERT INTO TEAM(TEAM_NAME,LEAGUE_NAME) VALUES ('Lamigo桃猿','中華職棒');
INSERT INTO TEAM(TEAM_NAME,LEAGUE_NAME) VALUES ('統一獅','中華職棒');
INSERT INTO TEAM(TEAM_NAME,LEAGUE_NAME) VALUES ('義大犀牛','中華職棒');
INSERT INTO TEAM(TEAM_NAME,LEAGUE_NAME) VALUES ('中信兄弟','中華職棒');
INSERT INTO TEAM(TEAM_NAME,LEAGUE_NAME) VALUES ('亞特蘭大勇士','美國職棒');
INSERT INTO TEAM(TEAM_NAME,LEAGUE_NAME) VALUES ('邁阿密馬林魚','美國職棒');
INSERT INTO TEAM(TEAM_NAME,LEAGUE_NAME) VALUES ('華盛頓國民','美國職棒');
INSERT INTO TEAM(TEAM_NAME,LEAGUE_NAME) VALUES ('紐約大都會','美國職棒');
INSERT INTO TEAM(TEAM_NAME,LEAGUE_NAME) VALUES ('費城費城人','美國職棒');
INSERT INTO TEAM(TEAM_NAME,LEAGUE_NAME) VALUES ('芝加哥小熊','美國職棒');
INSERT INTO TEAM(TEAM_NAME,LEAGUE_NAME) VALUES ('辛辛那堤紅人','美國職棒');
INSERT INTO TEAM(TEAM_NAME,LEAGUE_NAME) VALUES ('休士頓太空人','美國職棒');
INSERT INTO TEAM(TEAM_NAME,LEAGUE_NAME) VALUES ('密爾瓦基釀酒人','美國職棒');
INSERT INTO TEAM(TEAM_NAME,LEAGUE_NAME) VALUES ('匹茲堡海盜','美國職棒');
INSERT INTO TEAM(TEAM_NAME,LEAGUE_NAME) VALUES ('聖路易紅雀','美國職棒');
INSERT INTO TEAM(TEAM_NAME,LEAGUE_NAME) VALUES ('亞歷桑那響尾蛇','美國職棒');
INSERT INTO TEAM(TEAM_NAME,LEAGUE_NAME) VALUES ('科羅拉多落磯山','美國職棒');
INSERT INTO TEAM(TEAM_NAME,LEAGUE_NAME) VALUES ('洛杉磯道奇','美國職棒');
INSERT INTO TEAM(TEAM_NAME,LEAGUE_NAME) VALUES ('聖地牙哥教士隊','美國職棒');
INSERT INTO TEAM(TEAM_NAME,LEAGUE_NAME) VALUES ('舊金山巨人','美國職棒');
INSERT INTO TEAM(TEAM_NAME,LEAGUE_NAME) VALUES ('巴爾地摩金鶯','美國職棒');
INSERT INTO TEAM(TEAM_NAME,LEAGUE_NAME) VALUES ('波士頓紅襪隊','美國職棒');
INSERT INTO TEAM(TEAM_NAME,LEAGUE_NAME) VALUES ('紐約洋基隊','美國職棒');
INSERT INTO TEAM(TEAM_NAME,LEAGUE_NAME) VALUES ('坦帕灣魔鬼魚隊','美國職棒');
INSERT INTO TEAM(TEAM_NAME,LEAGUE_NAME) VALUES ('多倫多藍鳥','美國職棒');
INSERT INTO TEAM(TEAM_NAME,LEAGUE_NAME) VALUES ('芝加哥白襪隊','美國職棒');
INSERT INTO TEAM(TEAM_NAME,LEAGUE_NAME) VALUES ('克里夫蘭印地安人隊','美國職棒');
INSERT INTO TEAM(TEAM_NAME,LEAGUE_NAME) VALUES ('底特律老虎','美國職棒');
INSERT INTO TEAM(TEAM_NAME,LEAGUE_NAME) VALUES ('堪薩斯皇家','美國職棒');
INSERT INTO TEAM(TEAM_NAME,LEAGUE_NAME) VALUES ('明尼蘇達雙城','美國職棒');
INSERT INTO TEAM(TEAM_NAME,LEAGUE_NAME) VALUES ('安那漢天使','美國職棒');
INSERT INTO TEAM(TEAM_NAME,LEAGUE_NAME) VALUES ('奧克蘭運動家','美國職棒');
INSERT INTO TEAM(TEAM_NAME,LEAGUE_NAME) VALUES ('西雅圖水手','美國職棒');
INSERT INTO TEAM(TEAM_NAME,LEAGUE_NAME) VALUES ('德州遊騎兵','美國職棒');
INSERT INTO TEAM(TEAM_NAME,LEAGUE_NAME) VALUES ('讀賣巨人','中央聯盟');
INSERT INTO TEAM(TEAM_NAME,LEAGUE_NAME) VALUES ('阪神虎','中央聯盟');
INSERT INTO TEAM(TEAM_NAME,LEAGUE_NAME) VALUES ('中日龍','中央聯盟');
INSERT INTO TEAM(TEAM_NAME,LEAGUE_NAME) VALUES ('廣島東洋鯉魚','中央聯盟');
INSERT INTO TEAM(TEAM_NAME,LEAGUE_NAME) VALUES ('橫濱海灣之星','中央聯盟');
INSERT INTO TEAM(TEAM_NAME,LEAGUE_NAME) VALUES ('養樂多燕子','中央聯盟');
INSERT INTO TEAM(TEAM_NAME,LEAGUE_NAME) VALUES ('埼玉西武獅隊','太平洋聯盟');
INSERT INTO TEAM(TEAM_NAME,LEAGUE_NAME) VALUES ('北海道日本職棒火腿鬥士隊','太平洋聯盟');
INSERT INTO TEAM(TEAM_NAME,LEAGUE_NAME) VALUES ('東北樂天金鷲隊','太平洋聯盟');
INSERT INTO TEAM(TEAM_NAME,LEAGUE_NAME) VALUES ('福岡軟體銀行鷹隊','太平洋聯盟');
INSERT INTO TEAM(TEAM_NAME,LEAGUE_NAME) VALUES ('千葉羅德海洋隊','太平洋聯盟');
INSERT INTO TEAM(TEAM_NAME,LEAGUE_NAME) VALUES ('斗山熊','韓國職棒');
INSERT INTO TEAM(TEAM_NAME,LEAGUE_NAME) VALUES ('LG雙子','韓國職棒');
INSERT INTO TEAM(TEAM_NAME,LEAGUE_NAME) VALUES ('首爾英雄','韓國職棒');
INSERT INTO TEAM(TEAM_NAME,LEAGUE_NAME) VALUES ('SK飛龍','韓國職棒');
INSERT INTO TEAM(TEAM_NAME,LEAGUE_NAME) VALUES ('NC恐龍','韓國職棒');
INSERT INTO TEAM(TEAM_NAME,LEAGUE_NAME) VALUES ('三星獅','韓國職棒');
INSERT INTO TEAM(TEAM_NAME,LEAGUE_NAME) VALUES ('樂天巨人','韓國職棒');
INSERT INTO TEAM(TEAM_NAME,LEAGUE_NAME) VALUES ('韓華老鷹','韓國職棒');
INSERT INTO TEAM(TEAM_NAME,LEAGUE_NAME) VALUES ('起亞老虎','韓國職棒');
INSERT INTO TEAM(TEAM_NAME,LEAGUE_NAME) VALUES ('洛杉磯天使','美國職棒');

INSERT INTO game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END) VALUES ('2014-08-19T07:05:00',109,3,11,17,16,'Baseball','TRUE');
INSERT INTO game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END) VALUES ('2014-08-19T07:05:00',110,4,7,11,14,'Baseball','TRUE');
INSERT INTO game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END) VALUES ('2014-08-19T07:05:00',111,8,1,19,18,'Baseball','TRUE');
INSERT INTO game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END) VALUES ('2014-08-20T10:05:00',112,6,2,13,23,'Baseball','TRUE');
INSERT INTO game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END) VALUES ('2014-08-20T10:10:00',113,8,6,20,9,'Baseball','TRUE');
INSERT INTO game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END) VALUES ('2014-08-22T01:05:00',114,4,8,24,13,'Baseball','TRUE');
INSERT INTO game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END) VALUES ('2014-08-22T01:10:00',115,7,5,25,29,'Baseball','TRUE');
INSERT INTO game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END) VALUES ('2014-08-22T01:10:00',116,4,2,31,28,'Baseball','TRUE');
INSERT INTO game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END) VALUES ('2014-08-22T04:05:00',117,7,3,8,17,'Baseball','TRUE');
INSERT INTO game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END) VALUES ('2014-08-22T07:10:00',118,1,8,23,55,'Baseball','TRUE');
INSERT INTO game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END) VALUES ('2014-08-22T07:10:00',119,9,2,12,6,'Baseball','TRUE');
INSERT INTO game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END) VALUES ('2014-08-22T08:05:00',120,3,4,11,20,'Baseball','TRUE');
INSERT INTO game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END) VALUES ('2014-08-26T08:05:00',121,0,7,37,39,'Baseball','TRUE');
INSERT INTO game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END) VALUES ('2014-08-26T08:05:00',122,2,5,54,53,'Baseball','TRUE');
INSERT INTO game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END) VALUES ('2014-08-26T08:05:00',123,3,4,36,35,'Baseball','TRUE');
INSERT INTO game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END) VALUES ('2014-08-26T08:05:00',124,2,9,1,3,'Baseball','TRUE');
INSERT INTO game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END) VALUES ('2014-08-26T08:05:00',125,6,12,40,38,'Baseball','TRUE');
INSERT INTO game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END) VALUES ('2014-08-26T08:05:00',126,2,3,53,50,'Baseball','TRUE');
INSERT INTO game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END) VALUES ('2014-08-26T08:05:00',127,7,10,52,51,'Baseball','TRUE');
INSERT INTO game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END) VALUES ('2014-08-27T08:05:00',128,15,16,14,15,'Baseball','TRUE');
INSERT INTO game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END) VALUES ('2014-08-27T08:05:00',129,10,8,9,7,'Baseball','TRUE');
INSERT INTO game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END) VALUES ('2014-08-27T08:05:00',130,8,5,22,25,'Baseball','TRUE');
INSERT INTO game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END) VALUES ('2014-08-27T08:05:00',131,8,7,23,26,'Baseball','TRUE');
INSERT INTO game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END) VALUES ('2014-08-27T08:05:00',132,6,1,20,14,'Baseball','TRUE');
INSERT INTO game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END) VALUES ('2014-08-27T08:05:00',133,2,8,17,19,'Baseball','TRUE');
INSERT INTO game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END) VALUES ('2014-08-27T08:05:00',134,4,6,54,7,'Baseball','TRUE');
INSERT INTO game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END) VALUES ('2014-08-27T08:05:00',135,5,3,21,18,'Baseball','TRUE');
INSERT INTO game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END) VALUES ('2014-08-30T00:35:00',136,7,4,14,15,'Baseball','TRUE');
insert into game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END) VALUES ('2014-08-31T10:50:00',137,5,3,11,12,'Baseball','TRUE');
insert into game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END) VALUES ('2014-09-01T10:50:00',138,4,1,12,13,'Baseball','TRUE');
insert into game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END) VALUES ('2014-09-01T10:50:00',139,7,3,15,13,'Baseball','TRUE');
insert into game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END) VALUES ('2014-09-15T10:50:00',140,0,0,14,13,'Baseball','FALSE');
insert into game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END) VALUES ('2014-09-15T10:50:00',141,0,0,31,13,'Baseball','FALSE');
insert into game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END) values ('2014-09-19T07:05:00',142,0,0,11,33,'Baseball','FALSE');
insert into game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END) values ('2014-09-19T07:05:00',143,0,0,19,18,'Baseball','FALSE');
INSERT INTO game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END) VALUES ('2014-09-18T07:05:00',144,0,0,13,32,'Baseball','FALSE');
INSERT INTO game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END) VALUES ('2014-09-18T07:05:00',145,0,0,55,6,'Baseball','FALSE');
INSERT INTO game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END) VALUES ('2014-09-18T07:05:00',146,0,0,33,34,'Baseball','FALSE');
INSERT INTO game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END) VALUES ('2014-09-18T07:05:00',147,0,0,20,17,'Baseball','FALSE');
INSERT INTO game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END) VALUES ('2014-09-18T07:05:00',148,0,0,12,21,'Baseball','FALSE');
INSERT INTO game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END) VALUES ('2014-09-18T07:05:00',149,0,0,29,34,'Baseball','FALSE');
insert into game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END) VALUES ('2014-09-30T10:50:00',150,0,0,21,13,'Baseball','FALSE');
insert into game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END) VALUES ('2014-09-30T10:50:00',151,0,0,21,13,'Baseball','FALSE');

INSERT INTO game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END) VALUES ('2014-09-05T07:05:00',152,0,0,29,34,'Baseball','FALSE');
insert into game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END) VALUES ('2014-09-06T10:50:00',153,0,0,21,13,'Baseball','FALSE');
insert into game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END) VALUES ('2014-09-07T10:50:00',154,0,0,21,13,'Baseball','FALSE');

INSERT INTO USERN(USER_ACCOUNT,USER_PASSWORD,USER_NAME,USER_CARD_ID,USER_BIRTHDAY,USER_ADDRESS,USER_EMAIL,USER_BANK_ACCOUNT) VALUES('JACKYCHEN','a123123','王小蠻','A323456789','1988-11-11','Taipei','wang1@gmail.com','1234-5678-1111');
INSERT INTO USERN(USER_ACCOUNT,USER_PASSWORD,USER_NAME,USER_CARD_ID,USER_BIRTHDAY,USER_ADDRESS,USER_EMAIL,USER_BANK_ACCOUNT,USER_PHONE) VALUES('CHEN','a123456','王大蠻','A223456789','1988-11-11','Taipei','wang2@gmail.com','1234-5678-2222','0912345678');



insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (1, 'SU_H', 0, 1.70, 700, false);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (1, 'SU_A', 0, 1.25, 500, false);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (1, 'ATS_A', 1.5, 1.60, 400, false);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (1, 'ATS_H', -1.5, 1.90, 200, false);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (1, 'SC_H', 8.5, 1.70, 400, false);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (1, 'SC_L', 8.5, 1.80, 500, false);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (1, 'ODD', 0, 1.50, 600, false);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (1, 'EVEN', 0, 2.05, 700, false);

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (2, 'SU_H', 0, 1.85, 100, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (2, 'SU_A', 0, 1.65, 300, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (2, 'ATS_A', 1.5, 1.60, 400, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (2, 'ATS_H', -1.5, 1.90, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (2, 'SC_H', 8.5, 1.70, 600, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (2, 'SC_L', 8.5, 1.80, 800, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (2, 'ODD', 0, 1.50, 200, 'TRUE');

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (2, 'EVEN', 0, 2.05, 400, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (3, 'SU_H', 0, 1.70, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (3, 'SU_A', 0, 1.60, 600, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (3, 'ATS_A', 1.5, 1.60, 700, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (3, 'ATS_H', -1.5, 1.90, 900, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (3, 'SC_H', 8.5, 1.70, 300, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (3, 'SC_L', 8.5, 1.80, 600, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (3, 'ODD', 0, 1.50, 300, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (3, 'EVEN', 0, 2.05, 600, 'TRUE');

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (4, 'SU_H', 0, 1.20, 700, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (4, 'SU_A', 0, 2.10, 200, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (4, 'ATS_A', 1.5, 1.60, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (4, 'ATS_H', -1.5, 1.90, 300, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (4, 'SC_H', 8.5, 1.70, 100, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (4, 'SC_L', 8.5, 1.80, 800, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (4, 'ODD', 0, 1.50, 900, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (4, 'EVEN', 0, 2.05, 400, 'TRUE');

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (5, 'SU_H', 0, 1.85, 300, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (5, 'SU_A', 0, 1.35, 200, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (5, 'ATS_A', 1.5, 1.60, 400, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (5, 'ATS_H', -1.5, 1.90, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (5, 'SC_H', 8.5, 1.70, 600, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (5, 'SC_L', 8.5, 1.80, 300, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (5, 'ODD', 0, 1.50, 300, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (5, 'EVEN', 0, 2.05, 500, 'TRUE');

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (6, 'SU_H', 0, 1.75, 400, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (6, 'SU_A', 0, 1.75, 600, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (6, 'ATS_A', 1.5, 1.60, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (6, 'ATS_H', -1.5, 1.90, 200, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (6, 'SC_H', 8.5, 1.70, 600, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (6, 'SC_L', 8.5, 1.80, 300, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (6, 'ODD', 0, 1.50, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (6, 'EVEN', 0, 2.05, 700, 'TRUE');

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (7, 'SU_H', 0, 1.95, 300, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (7, 'SU_A', 0, 1.45, 100, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (7, 'ATS_A', 1.5, 1.60, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (7, 'ATS_H', -1.5, 1.90, 700, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (7, 'SC_H', 8.5, 1.70, 300, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (7, 'SC_L', 8.5, 1.80, 400, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (7, 'ODD', 0, 1.50, 600, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (7, 'EVEN', 0, 2.05, 700, 'TRUE');

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (8, 'SU_H', 0, 1.25, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (8, 'SU_A', 0, 2.15, 800, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (8, 'ATS_A', 1.5, 1.60, 900, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (8, 'ATS_H', -1.5, 1.90, 200, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (8, 'SC_H', 8.5, 1.70, 400, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (8, 'SC_L', 8.5, 1.80, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (8, 'ODD', 0, 1.50, 600, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (8, 'EVEN', 0, 2.05, 700, 'TRUE');

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (9, 'SU_A', 0, 2.15, 800, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (9, 'SU_H', 0, 1.45, 300, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (9, 'ATS_A', 1.5, 1.60, 200, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (9, 'ATS_H', -1.5, 1.90, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (9, 'SC_H', 8.5, 1.70, 300, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (9, 'SC_L', 8.5, 1.80, 700, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (9, 'ODD', 0, 1.50, 600, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (9, 'EVEN', 0, 2.05, 400, 'TRUE');

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (10, 'SU_A', 0, 2.15, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (10, 'SU_H', 0, 1.45, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (10, 'ATS_A', 1.5, 1.60, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (10, 'ATS_H', -1.5, 1.90, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (10, 'SC_H', 7.5, 1.85, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (10, 'SC_L', 7.5, 1.65, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (10, 'ODD', 0, 1.50, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (10, 'EVEN', 0, 2.05, 500, 'TRUE');

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (11, 'SU_A', 0, 2.85, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (11, 'SU_H', 0, 1.25, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (11, 'ATS_A', 1.5, 1.95, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (11, 'ATS_H', -1.5, 1.55, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (11, 'SC_H', 6.5, 1.60, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (11, 'SC_L', 6.5, 1.90, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (11, 'ODD', 0, 1.50, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (11, 'EVEN', 0, 2.05, 500, 'TRUE');

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (12, 'SU_A', 0, 2.85, 100, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (12, 'SU_H', 0, 1.25, 220, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (12, 'ATS_A', 1.5, 1.95, 333, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (12, 'ATS_H', -1.5, 1.55, 400, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (12, 'SC_H', 6.5, 1.60, 560, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (12, 'SC_L', 6.5, 1.90, 607, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (12, 'ODD', 0, 1.50, 899, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (12, 'EVEN', 0, 2.05, 20, 'TRUE');

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (13, 'SU_A', 0, 2.85, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (13, 'SU_H', 0, 1.25, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (13, 'ATS_A', 1.5, 1.95, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (13, 'ATS_H', -1.5, 1.55, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (13, 'SC_H', 6.5, 1.60, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (13, 'SC_L', 6.5, 1.90, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (13, 'ODD', 0, 1.50, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (13, 'EVEN', 0, 2.05, 500, 'TRUE');

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (14, 'SU_A', 0, 2.85, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (14, 'SU_H', 0, 1.25, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (14, 'ATS_A', 1.5, 1.95, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (14, 'ATS_H', -1.5, 1.55, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (14, 'SC_H', 6.5, 1.60, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (14, 'SC_L', 6.5, 1.90, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (14, 'ODD', 0, 1.50, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (14, 'EVEN', 0, 2.05, 500, 'TRUE');

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (15, 'SU_A', 0, 2.85, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (15, 'SU_H', 0, 1.25, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (15, 'ATS_A', 1.5, 1.95, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (15, 'ATS_H', -1.5, 1.55, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (15, 'SC_H', 6.5, 1.60, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (15, 'SC_L', 6.5, 1.90, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (15, 'ODD', 0, 1.50, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (15, 'EVEN', 0, 2.05, 500, 'TRUE');

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (16, 'SU_A', 0, 2.85, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (16, 'SU_H', 0, 1.25, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (16, 'ATS_A', 1.5, 1.95, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (16, 'ATS_H', -1.5, 1.55, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (16, 'SC_H', 6.5, 1.60, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (16, 'SC_L', 6.5, 1.90, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (16, 'ODD', 0, 1.50, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (16, 'EVEN', 0, 2.05, 500, 'TRUE');

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (17, 'SU_A', 0, 2.85, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (17, 'SU_H', 0, 1.25, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (17, 'ATS_A', 1.5, 1.95, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (17, 'ATS_H', -1.5, 1.55, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (17, 'SC_H', 6.5, 1.60, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (17, 'SC_L', 6.5, 1.90, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (17, 'ODD', 0, 1.50, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (17, 'EVEN', 0, 2.05, 500, 'TRUE');

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (18, 'SU_H', 0, 1.25, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (18, 'SU_A', 0, 2.15, 800, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (18, 'ATS_A', 1.5, 1.60, 900, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (18, 'ATS_H', -1.5, 1.90, 200, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (18, 'SC_H', 8.5, 1.70, 400, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (18, 'SC_L', 8.5, 1.80, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (18, 'ODD', 0, 1.50, 600, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (18, 'EVEN', 0, 2.05, 700, 'TRUE');

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (19, 'SU_A', 0, 2.15, 800, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (19, 'SU_H', 0, 1.45, 300, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (19, 'ATS_A', 1.5, 1.60, 200, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (19, 'ATS_H', -1.5, 1.90, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (19, 'SC_H', 8.5, 1.70, 300, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (19, 'SC_L', 8.5, 1.80, 700, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (19, 'ODD', 0, 1.50, 600, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (19, 'EVEN', 0, 2.05, 400, 'TRUE');

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (20, 'SU_H', 0, 1.70, 0, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (20, 'SU_A', 0, 1.25, 0, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (20, 'ATS_A', 1.5, 1.60, 0, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (20, 'ATS_H', -1.5, 1.90, 0, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (20, 'SC_H', 8.5, 1.70, 0, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (20, 'SC_L', 8.5, 1.80, 0, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (20, 'ODD', 0, 1.50, 0, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (20, 'EVEN', 0, 2.05, 0, null);

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (21, 'SU_H', 0, 1.70, 700, false);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (21, 'SU_A', 0, 1.25, 500, false);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (21, 'ATS_A', 1.5, 1.60, 400, false);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (21, 'ATS_H', -1.5, 1.90, 200, false);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (21, 'SC_H', 8.5, 1.70, 400, false);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (21, 'SC_L', 8.5, 1.80, 500, false);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (21, 'ODD', 0, 1.50, 600, false);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (21, 'EVEN', 0, 2.05, 700, false);

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (22, 'SU_H', 0, 1.85, 100, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (22, 'SU_A', 0, 1.65, 300, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (22, 'ATS_A', 1.5, 1.60, 400, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (22, 'ATS_H', -1.5, 1.90, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (22, 'SC_H', 8.5, 1.70, 600, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (22, 'SC_L', 8.5, 1.80, 800, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (22, 'ODD', 0, 1.50, 200, 'TRUE');

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (22, 'EVEN', 0, 2.05, 400, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (23, 'SU_H', 0, 1.70, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (23, 'SU_A', 0, 1.60, 600, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (23, 'ATS_A', 1.5, 1.60, 700, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (23, 'ATS_H', -1.5, 1.90, 900, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (23, 'SC_H', 8.5, 1.70, 300, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (23, 'SC_L', 8.5, 1.80, 600, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (23, 'ODD', 0, 1.50, 300, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (23, 'EVEN', 0, 2.05, 600, 'TRUE');

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (24, 'SU_H', 0, 1.20, 700, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (24, 'SU_A', 0, 2.10, 200, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (24, 'ATS_A', 1.5, 1.60, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (24, 'ATS_H', -1.5, 1.90, 300, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (24, 'SC_H', 8.5, 1.70, 100, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (24, 'SC_L', 8.5, 1.80, 800, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (24, 'ODD', 0, 1.50, 900, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (24, 'EVEN', 0, 2.05, 400, 'TRUE');

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (25, 'SU_H', 0, 1.85, 300, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (25, 'SU_A', 0, 1.35, 200, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (25, 'ATS_A', 1.5, 1.60, 400, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (25, 'ATS_H', -1.5, 1.90, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (25, 'SC_H', 8.5, 1.70, 600, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (25, 'SC_L', 8.5, 1.80, 300, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (25, 'ODD', 0, 1.50, 300, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (25, 'EVEN', 0, 2.05, 500, 'TRUE');

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (26, 'SU_H', 0, 1.75, 400, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (26, 'SU_A', 0, 1.75, 600, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (26, 'ATS_A', 1.5, 1.60, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (26, 'ATS_H', -1.5, 1.90, 200, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (26, 'SC_H', 8.5, 1.70, 600, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (26, 'SC_L', 8.5, 1.80, 300, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (26, 'ODD', 0, 1.50, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (26, 'EVEN', 0, 2.05, 700, 'TRUE');

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (27, 'SU_H', 0, 1.95, 300, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (27, 'SU_A', 0, 1.45, 100, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (27, 'ATS_A', 1.5, 1.60, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (27, 'ATS_H', -1.5, 1.90, 700, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (27, 'SC_H', 8.5, 1.70, 300, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (27, 'SC_L', 8.5, 1.80, 400, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (27, 'ODD', 0, 1.50, 600, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (27, 'EVEN', 0, 2.05, 700, 'TRUE');

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (28, 'SU_H', 0, 1.25, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (28, 'SU_A', 0, 2.15, 800, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (28, 'ATS_A', 1.5, 1.60, 900, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (28, 'ATS_H', -1.5, 1.90, 200, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (28, 'SC_H', 8.5, 1.70, 400, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (28, 'SC_L', 8.5, 1.80, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (28, 'ODD', 0, 1.50, 600, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (28, 'EVEN', 0, 2.05, 700, 'TRUE');

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (29, 'SU_A', 0, 2.15, 800, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (29, 'SU_H', 0, 1.45, 300, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (29, 'ATS_A', 1.5, 1.60, 200, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (29, 'ATS_H', -1.5, 1.90, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (29, 'SC_H', 8.5, 1.70, 300, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (29, 'SC_L', 8.5, 1.80, 700, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (29, 'ODD', 0, 1.50, 600, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (29, 'EVEN', 0, 2.05, 400, 'TRUE');

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (30, 'SU_A', 0, 2.15, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (30, 'SU_H', 0, 1.45, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (30, 'ATS_A', 1.5, 1.60, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (30, 'ATS_H', -1.5, 1.90, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (30, 'SC_H', 7.5, 1.85, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (30, 'SC_L', 7.5, 1.65, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (30, 'ODD', 0, 1.50, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (30, 'EVEN', 0, 2.05, 500, 'TRUE');

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (31, 'SU_A', 0, 2.85, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (31, 'SU_H', 0, 1.25, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (31, 'ATS_A', 1.5, 1.95, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (31, 'ATS_H', -1.5, 1.55, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (31, 'SC_H', 6.5, 1.60, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (31, 'SC_L', 6.5, 1.90, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (31, 'ODD', 0, 1.50, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (31, 'EVEN', 0, 2.05, 500, 'TRUE');

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (32, 'SU_A', 0, 2.85, 100, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (32, 'SU_H', 0, 1.25, 220, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (32, 'ATS_A', 1.5, 1.95, 333, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (32, 'ATS_H', -1.5, 1.55, 400, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (32, 'SC_H', 6.5, 1.60, 560, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (32, 'SC_L', 6.5, 1.90, 607, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (32, 'ODD', 0, 1.50, 899, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (32, 'EVEN', 0, 2.05, 20, 'TRUE');

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (33, 'SU_A', 0, 2.85, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (33, 'SU_H', 0, 1.25, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (33, 'ATS_A', 1.5, 1.95, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (33, 'ATS_H', -1.5, 1.55, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (33, 'SC_H', 6.5, 1.60, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (33, 'SC_L', 6.5, 1.90, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (33, 'ODD', 0, 1.50, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (33, 'EVEN', 0, 2.05, 500, 'TRUE');

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (34, 'SU_A', 0, 2.85, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (34, 'SU_H', 0, 1.25, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (34, 'ATS_A', 1.5, 1.95, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (34, 'ATS_H', -1.5, 1.55, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (34, 'SC_H', 6.5, 1.60, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (34, 'SC_L', 6.5, 1.90, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (34, 'ODD', 0, 1.50, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (34, 'EVEN', 0, 2.05, 500, 'TRUE');

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (35, 'SU_A', 0, 2.85, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (35, 'SU_H', 0, 1.25, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (35, 'ATS_A', 1.5, 1.95, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (35, 'ATS_H', -1.5, 1.55, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (35, 'SC_H', 6.5, 1.60, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (35, 'SC_L', 6.5, 1.90, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (35, 'ODD', 0, 1.50, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (35, 'EVEN', 0, 2.05, 500, 'TRUE');

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (36, 'SU_A', 0, 2.85, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (36, 'SU_H', 0, 1.25, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (36, 'ATS_A', 1.5, 1.95, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (36, 'ATS_H', -1.5, 1.55, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (36, 'SC_H', 6.5, 1.60, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (36, 'SC_L', 6.5, 1.90, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (36, 'ODD', 0, 1.50, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (36, 'EVEN', 0, 2.05, 500, 'TRUE');

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (37, 'SU_A', 0, 2.85, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (37, 'SU_H', 0, 1.25, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (37, 'ATS_A', 1.5, 1.95, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (37, 'ATS_H', -1.5, 1.55, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (37, 'SC_H', 6.5, 1.60, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (37, 'SC_L', 6.5, 1.90, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (37, 'ODD', 0, 1.50, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (37, 'EVEN', 0, 2.05, 500, 'TRUE');

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (38, 'SU_H', 0, 1.25, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (38, 'SU_A', 0, 2.15, 800, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (38, 'ATS_A', 1.5, 1.60, 900, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (38, 'ATS_H', -1.5, 1.90, 200, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (38, 'SC_H', 8.5, 1.70, 400, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (38, 'SC_L', 8.5, 1.80, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (38, 'ODD', 0, 1.50, 600, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (38, 'EVEN', 0, 2.05, 700, 'TRUE');

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (39, 'SU_A', 0, 2.15, 800, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (39, 'SU_H', 0, 1.45, 300, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (39, 'ATS_A', 1.5, 1.60, 200, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (39, 'ATS_H', -1.5, 1.90, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (39, 'SC_H', 8.5, 1.70, 300, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (39, 'SC_L', 8.5, 1.80, 700, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (39, 'ODD', 0, 1.50, 600, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (39, 'EVEN', 0, 2.05, 400, 'TRUE');

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (40, 'SU_H', 0, 1.70, 0, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (40, 'SU_A', 0, 1.25, 0, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (40, 'ATS_A', 1.5, 1.60, 0, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (40, 'ATS_H', -1.5, 1.90, 0, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (40, 'SC_H', 8.5, 1.70, 0, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (40, 'SC_L', 8.5, 1.80, 0, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (40, 'ODD', 0, 1.50, 0, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (40, 'EVEN', 0, 2.05, 0, null);

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (41, 'SU_A', 0, 2.85, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (41, 'SU_H', 0, 1.25, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (41, 'ATS_A', 1.5, 1.95, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (41, 'ATS_H', -1.5, 1.55, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (41, 'SC_H', 6.5, 1.60, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (41, 'SC_L', 6.5, 1.90, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (41, 'ODD', 0, 1.50, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (41, 'EVEN', 0, 2.05, 500, null);

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (42, 'SU_A', 0, 2.85, 100, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (42, 'SU_H', 0, 1.25, 220, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (42, 'ATS_A', 1.5, 1.95, 333, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (42, 'ATS_H', -1.5, 1.55, 400, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (42, 'SC_H', 6.5, 1.60, 560, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (42, 'SC_L', 6.5, 1.90, 607, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (42, 'ODD', 0, 1.50, 899, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (42, 'EVEN', 0, 2.05, 20, null);

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (43, 'SU_A', 0, 2.85, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (43, 'SU_H', 0, 1.25, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (43, 'ATS_A', 1.5, 1.95, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (43, 'ATS_H', -1.5, 1.55, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (43, 'SC_H', 6.5, 1.60, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (43, 'SC_L', 6.5, 1.90, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (43, 'ODD', 0, 1.50, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (43, 'EVEN', 0, 2.05, 500, null);

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (44, 'SU_A', 0, 2.85, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (44, 'SU_H', 0, 1.25, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (44, 'ATS_A', 1.5, 1.95, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (44, 'ATS_H', -1.5, 1.55, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (44, 'SC_H', 6.5, 1.60, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (44, 'SC_L', 6.5, 1.90, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (44, 'ODD', 0, 1.50, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (44, 'EVEN', 0, 2.05, 500, null);

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (45, 'SU_A', 0, 2.85, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (45, 'SU_H', 0, 1.25, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (45, 'ATS_A', 1.5, 1.95, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (45, 'ATS_H', -1.5, 1.55, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (45, 'SC_H', 6.5, 1.60, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (45, 'SC_L', 6.5, 1.90, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (45, 'ODD', 0, 1.50, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (45, 'EVEN', 0, 2.05, 500, null);

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (46, 'SU_A', 0, 2.85, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (46, 'SU_H', 0, 1.25, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (46, 'ATS_A', 1.5, 1.95, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (46, 'ATS_H', -1.5, 1.55, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (46, 'SC_H', 6.5, 1.60, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (46, 'SC_L', 6.5, 1.90, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (46, 'ODD', 0, 1.50, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (46, 'EVEN', 0, 2.05, 500, null);

insert into lottery (USER_ID, WIN, CAPITAL, CONFIRM_TIME) values (1,100,1000,'2014-08-08T10:50:20');
insert into lottery (USER_ID, WIN, CAPITAL, CONFIRM_TIME) values (1,200,1000,'2014-08-09T10:50:20');
insert into lottery (USER_ID, WIN, CAPITAL, CONFIRM_TIME) values (1,1000,500,'2014-08-10T10:50:20');
insert into lottery (USER_ID, WIN, CAPITAL, CONFIRM_TIME) values (2,-1,300,'2014-08-10T10:50:20');
insert into lottery (USER_ID, WIN, CAPITAL, CONFIRM_TIME) values (2,-1,400,'2014-08-10T10:50:20');
insert into lottery (USER_ID, WIN, CAPITAL, CONFIRM_TIME) values (2,-1,300,'2014-08-10T10:50:20');

insert into lottery_odds (lottery_id, odds_id) values (4, 361);
insert into lottery_odds (lottery_id, odds_id) values (4, 363);
insert into lottery_odds (lottery_id, odds_id) values (4, 365);
insert into lottery_odds (lottery_id, odds_id) values (5, 362);
insert into lottery_odds (lottery_id, odds_id) values (5, 364);
insert into lottery_odds (lottery_id, odds_id) values (5, 366);
insert into lottery_odds (lottery_id, odds_id) values (5, 368);
insert into lottery_odds (lottery_id, odds_id) values (6, 362);

insert into depositCard (CARD_ACCOUNT, CARD_PASSWORD, POINT, USE_TIME, STATE) values ('aaa', 'bbb', 1000, null, true);

insert into announce (announce_title, announce_content, announce_time, modified_time) values ('測試公告1', '測試公告內容1', '2014-08-10T10:50:20', '2014-08-12T7:20:50');
insert into announce (announce_title, announce_content, announce_time, modified_time) values ('測試公告2', '測試公告內容2', '2014-08-13T8:20:10', '2014-08-13T8:21:45');
insert into announce (announce_title, announce_content, announce_time, modified_time) values ('測試公告3', '測試公告內容3', '2014-08-14T10:00:00', '2014-08-15T10:30:00');

insert into admin_log (profit, entered_time) values (6486, '2014-7-8T11:47:3');
insert into admin_log (profit, entered_time) values (923, '2014-9-30T8:40:4');
insert into admin_log (profit, entered_time) values (6043, '2014-9-22T20:54:8');
insert into admin_log (profit, entered_time) values (-310, '2014-8-12T12:37:17');
insert into admin_log (profit, entered_time) values (-1102, '2014-1-17T7:17:48');
insert into admin_log (profit, entered_time) values (-1497, '2014-1-7T2:16:51');
insert into admin_log (profit, entered_time) values (-2619, '2014-1-16T11:7:57');
insert into admin_log (profit, entered_time) values (2713, '2014-4-12T18:47:17');
insert into admin_log (profit, entered_time) values (5874, '2014-11-27T5:15:50');
insert into admin_log (profit, entered_time) values (5367, '2014-2-26T15:58:30');
insert into admin_log (profit, entered_time) values (3717, '2014-7-4T17:39:22');
insert into admin_log (profit, entered_time) values (-68, '2014-3-10T9:51:31');
insert into admin_log (profit, entered_time) values (4808, '2014-5-11T20:46:54');
insert into admin_log (profit, entered_time) values (3323, '2014-5-17T16:20:53');
insert into admin_log (profit, entered_time) values (5841, '2014-12-10T4:48:42');
insert into admin_log (profit, entered_time) values (-2111, '2014-6-11T23:36:30');
insert into admin_log (profit, entered_time) values (-2903, '2014-4-8T2:55:16');
insert into admin_log (profit, entered_time) values (-2699, '2014-5-12T19:5:27');
insert into admin_log (profit, entered_time) values (477, '2014-7-17T23:12:23');
insert into admin_log (profit, entered_time) values (-2837, '2014-2-28T3:29:25');