/*
INSERT INTO game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END,GAME_STATUS) VALUES ('2014-09-10T17:35:00',101,4,3,9,4,'Baseball','TRUE',2);
INSERT INTO game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END,GAME_STATUS) VALUES ('2014-09-10T17:25:00',102,4,3,13,10,'Baseball','TRUE',2);
INSERT INTO game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END,GAME_STATUS) VALUES ('2014-09-10T17:15:00',103,2,9,18,15,'Baseball','TRUE',2);
INSERT INTO game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END,GAME_STATUS) VALUES ('2014-09-10T17:05:00',104,2,4,7,5,'Baseball','TRUE',2);
INSERT INTO game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END,GAME_STATUS) VALUES ('2014-09-10T10:12:00',105,4,1,1,2,'Baseball','TRUE',2);
INSERT INTO game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END,GAME_STATUS) VALUES ('2014-09-10T03:55:00',106,9,3,8,14,'Baseball','TRUE',2);
INSERT INTO game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END,GAME_STATUS) VALUES ('2014-09-10T04:10:00',107,11,2,11,3,'Baseball','TRUE',2);
INSERT INTO game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END,GAME_STATUS) VALUES ('2014-09-10T01:10:00',108,2,1,6,12,'Baseball','TRUE',2);
INSERT INTO game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END,GAME_STATUS) VALUES ('2014-09-11T17:06:02',109,10,6,1,2,'Baseball','TRUE',2);
INSERT INTO game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END,GAME_STATUS) VALUES ('2014-09-11T17:04:01',110,1,11,18,15,'Baseball','TRUE',2);
INSERT INTO game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END,GAME_STATUS) VALUES ('2014-09-11T17:05:05',111,5,8,13,10,'Baseball','TRUE',2);
INSERT INTO game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END,GAME_STATUS) VALUES ('2014-09-11T08:05:08',112,3,0,7,5,'Baseball','TRUE',2);
INSERT INTO game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END,GAME_STATUS) VALUES ('2014-09-11T12:05:09',113,1,2,11,3,'Baseball','TRUE',2);
INSERT INTO game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END,GAME_STATUS) VALUES ('2014-09-11T11:05:10',114,8,1,8,14,'Baseball','TRUE',2);
INSERT INTO game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END,GAME_STATUS) VALUES ('2014-09-11T01:05:20',115,5,2,6,12,'Baseball','TRUE',2);
INSERT INTO game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END,GAME_STATUS) VALUES ('2014-09-12T02:05:30',116,2,8,9,4,'Baseball','TRUE',2);
INSERT INTO game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END,GAME_STATUS) VALUES ('2014-09-12T03:05:40',117,0,1,11,3,'Baseball','TRUE',2);
INSERT INTO game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END,GAME_STATUS) VALUES ('2014-09-12T19:05:50',118,0,2,9,4,'Baseball','TRUE',2);
INSERT INTO game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END,GAME_STATUS) VALUES ('2014-09-15T08:05:01',119,6,5,13,15,'Baseball','TRUE',2);
INSERT INTO game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END,GAME_STATUS) VALUES ('2014-09-15T08:15:02',120,4,6,4,5,'Baseball','TRUE',2);
INSERT INTO game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END,GAME_STATUS) VALUES ('2014-09-15T08:25:03',121,6,4,9,3,'Baseball','TRUE',2);
INSERT INTO game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END,GAME_STATUS) VALUES ('2014-09-16T08:35:01',122,0,1,10,13,'Baseball','TRUE',2);
INSERT INTO game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END,GAME_STATUS) VALUES ('2014-09-16T08:45:02',123,2,5,15,1,'Baseball','TRUE',2);
INSERT INTO game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END,GAME_STATUS) VALUES ('2014-09-16T08:55:00',124,3,4,3,7,'Baseball','TRUE',2);
INSERT INTO game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END,GAME_STATUS) VALUES ('2014-09-17T09:05:00',125,2,8,15,1,'Baseball','TRUE',2);
INSERT INTO game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END,GAME_STATUS) VALUES ('2014-09-17T10:05:00',126,1,6,10,13,'Baseball','TRUE',2);
INSERT INTO game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END,GAME_STATUS) VALUES ('2014-09-17T11:05:00',127,7,5,3,7,'Baseball','TRUE',2);
INSERT INTO game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END,GAME_STATUS) VALUES ('2014-09-18T00:35:00',128,3,2,10,13,'Baseball','TRUE',1);
insert into game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END,GAME_STATUS) VALUES ('2014-09-18T10:10:00',129,1,6,15,1,'Baseball','TRUE',1);
insert into game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END,GAME_STATUS) VALUES ('2014-09-18T10:20:00',130,2,6,3,7,'Baseball','TRUE',1);
insert into game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END,GAME_STATUS) VALUES ('2014-09-19T12:50:00',131,7,2,14,11,'Baseball',false,1);
insert into game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END,GAME_STATUS) VALUES ('2014-09-19T10:50:00',132,2,3,15,10,'Baseball',false,1);
insert into game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END,GAME_STATUS) VALUES ('2014-09-19T11:50:00',133,2,3,2,26,'Baseball',false,1);
insert into game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END,GAME_STATUS) values ('2014-09-20T02:20:00',134,0,0,21,18,'Baseball',false,1);
insert into game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END,GAME_STATUS) values ('2014-09-20T07:05:00',135,0,0,23,26,'Baseball',false,1);
INSERT INTO game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END,GAME_STATUS) VALUES ('2014-09-20T07:05:00',136,0,0,15,10,'Baseball',false,1);
INSERT INTO game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END,GAME_STATUS) VALUES ('2014-09-21T01:05:00',137,0,0,21,18,'Baseball',false,1);
INSERT INTO game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END,GAME_STATUS) VALUES ('2014-09-21T01:05:00',138,0,0,5,7,'Baseball',false,1);
insert into game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END,GAME_STATUS) VALUES (current_timestamp,139,0,0,25,11,'Baseball',false,1);
INSERT INTO game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END,GAME_STATUS) VALUES (current_timestamp,140,0,0,20,17,'Baseball',false,1);
INSERT INTO game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END,GAME_STATUS) VALUES (timestamp 'tomorrow',141,0,0,12,21,'Baseball',false,1);
INSERT INTO game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END,GAME_STATUS) VALUES (timestamp 'tomorrow',142,0,0,29,30,'Baseball',false,1);
insert into game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END,GAME_STATUS) VALUES ('2014-09-22T01:05:00',143,0,0,15,10,'Baseball',false,1);
INSERT INTO game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END,GAME_STATUS) VALUES ('2014-09-22T01:10:00',144,0,0,30,22,'Baseball',false,1);
insert into game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END,GAME_STATUS) VALUES ('2014-09-23T07:05:00',145,0,0,7,4,'Baseball',false,1);
insert into game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END,GAME_STATUS) VALUES ('2014-09-23T08:05:00',146,0,0,1,10,'Baseball',false,1);
insert into game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END,GAME_STATUS) VALUES (timestamp 'tomorrow',147,0,0,15,10,'Baseball',false,1);
INSERT INTO game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END,GAME_STATUS) VALUES (timestamp 'tomorrow',148,0,0,30,22,'Baseball',false,1);
insert into game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END,GAME_STATUS) VALUES (timestamp 'tomorrow',149,0,0,7,4,'Baseball',false,1);
insert into game (GAME_TIME, GAME_NUM, GAME_SCORE_HOME,GAME_SCORE_AWAY,TEAM_HOME,TEAM_AWAY,BALL_TYPE,IS_END,GAME_STATUS) VALUES (timestamp 'tomorrow',150,0,0,1,10,'Baseball',false,1);
*/

/*
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (1, 'SU_H', 0, 1.70, 700, false);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (1, 'SU_A', 0, 1.25, 500, false);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (1, 'ATS_A', 1.5, 1.60, 400, false);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (1, 'ATS_H', -1.5, 1.90, 200, false);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (1, 'SC_H', 8.5, 1.70, 400, false);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (1, 'SC_L', 8.5, 1.80, 500, false);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (1, 'ODD', 0, 1.50, 600, false);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (1, 'EVEN', 0, 2.05, 700, false);

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (2, 'SU_H', 0, 1.85, 100, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (2, 'SU_A', 0, 1.65, 300, 'False');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (2, 'ATS_A', 1.5, 1.60, 400, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (2, 'ATS_H', -1.5, 1.90, 500, 'false');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (2, 'SC_H', 8.5, 1.70, 600, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (2, 'SC_L', 8.5, 1.80, 800, 'false');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (2, 'ODD', 0, 1.50, 200, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (2, 'EVEN', 0, 2.05, 400, 'false');

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (3, 'SU_H', 0, 1.70, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (3, 'SU_A', 0, 1.60, 600, 'False');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (3, 'ATS_A', 1.5, 1.60, 700, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (3, 'ATS_H', -1.5, 1.90, 900, 'False');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (3, 'SC_H', 8.5, 1.70, 300, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (3, 'SC_L', 8.5, 1.80, 600, 'False');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (3, 'ODD', 0, 1.50, 300, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (3, 'EVEN', 0, 2.05, 600, 'False');

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (4, 'SU_H', 0, 1.20, 700, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (4, 'SU_A', 0, 2.10, 200, 'False');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (4, 'ATS_A', 1.5, 1.60, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (4, 'ATS_H', -1.5, 1.90, 300, 'False');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (4, 'SC_H', 8.5, 1.70, 100, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (4, 'SC_L', 8.5, 1.80, 800, 'False');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (4, 'ODD', 0, 1.50, 900, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (4, 'EVEN', 0, 2.05, 400, 'False');

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (5, 'SU_H', 0, 1.85, 300, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (5, 'SU_A', 0, 1.35, 200, 'False');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (5, 'ATS_A', 1.5, 1.60, 400, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (5, 'ATS_H', -1.5, 1.90, 500, 'False');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (5, 'SC_H', 8.5, 1.70, 600, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (5, 'SC_L', 8.5, 1.80, 300, 'False');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (5, 'ODD', 0, 1.50, 300, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (5, 'EVEN', 0, 2.05, 500, 'False');

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (6, 'SU_H', 0, 1.75, 400, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (6, 'SU_A', 0, 1.75, 600, 'False');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (6, 'ATS_A', 1.5, 1.60, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (6, 'ATS_H', -1.5, 1.90, 200, 'False');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (6, 'SC_H', 8.5, 1.70, 600, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (6, 'SC_L', 8.5, 1.80, 300, 'False');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (6, 'ODD', 0, 1.50, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (6, 'EVEN', 0, 2.05, 700, 'False');

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (7, 'SU_H', 0, 1.95, 300, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (7, 'SU_A', 0, 1.45, 100, 'False');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (7, 'ATS_A', 1.5, 1.60, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (7, 'ATS_H', -1.5, 1.90, 700, 'False');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (7, 'SC_H', 8.5, 1.70, 300, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (7, 'SC_L', 8.5, 1.80, 400, 'False');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (7, 'ODD', 0, 1.50, 600, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (7, 'EVEN', 0, 2.05, 700, 'False');

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (8, 'SU_H', 0, 1.25, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (8, 'SU_A', 0, 2.15, 800, 'False');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (8, 'ATS_A', 1.5, 1.60, 900, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (8, 'ATS_H', -1.5, 1.90, 200, 'False');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (8, 'SC_H', 8.5, 1.70, 400, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (8, 'SC_L', 8.5, 1.80, 500, 'False');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (8, 'ODD', 0, 1.50, 600, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (8, 'EVEN', 0, 2.05, 700, 'False');

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (9, 'SU_A', 0, 2.15, 800, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (9, 'SU_H', 0, 1.45, 300, 'False');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (9, 'ATS_A', 1.5, 1.60, 200, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (9, 'ATS_H', -1.5, 1.90, 500, 'False');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (9, 'SC_H', 8.5, 1.70, 300, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (9, 'SC_L', 8.5, 1.80, 700, 'False');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (9, 'ODD', 0, 1.50, 600, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (9, 'EVEN', 0, 2.05, 400, 'False');

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (10, 'SU_A', 0, 2.15, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (10, 'SU_H', 0, 1.45, 500, 'False');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (10, 'ATS_A', 1.5, 1.60, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (10, 'ATS_H', -1.5, 1.90, 500, 'False');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (10, 'SC_H', 7.5, 1.85, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (10, 'SC_L', 7.5, 1.65, 500, 'False');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (10, 'ODD', 0, 1.50, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (10, 'EVEN', 0, 2.05, 500, 'False');

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (11, 'SU_A', 0, 2.85, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (11, 'SU_H', 0, 1.25, 500, 'False');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (11, 'ATS_A', 1.5, 1.95, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (11, 'ATS_H', -1.5, 1.55, 500, 'False');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (11, 'SC_H', 6.5, 1.60, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (11, 'SC_L', 6.5, 1.90, 500, 'False');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (11, 'ODD', 0, 1.50, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (11, 'EVEN', 0, 2.05, 500, 'False');

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (12, 'SU_A', 0, 2.85, 100, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (12, 'SU_H', 0, 1.25, 220, 'False');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (12, 'ATS_A', 1.5, 1.95, 333, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (12, 'ATS_H', -1.5, 1.55, 400, 'False');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (12, 'SC_H', 6.5, 1.60, 560, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (12, 'SC_L', 6.5, 1.90, 607, 'False');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (12, 'ODD', 0, 1.50, 899, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (12, 'EVEN', 0, 2.05, 20, 'False');

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (13, 'SU_A', 0, 2.85, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (13, 'SU_H', 0, 1.25, 500, 'False');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (13, 'ATS_A', 1.5, 1.95, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (13, 'ATS_H', -1.5, 1.55, 500, 'False');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (13, 'SC_H', 6.5, 1.60, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (13, 'SC_L', 6.5, 1.90, 500, 'False');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (13, 'ODD', 0, 1.50, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (13, 'EVEN', 0, 2.05, 500, 'False');

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (14, 'SU_A', 0, 2.85, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (14, 'SU_H', 0, 1.25, 500, 'False');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (14, 'ATS_A', 1.5, 1.95, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (14, 'ATS_H', -1.5, 1.55, 500, 'False');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (14, 'SC_H', 6.5, 1.60, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (14, 'SC_L', 6.5, 1.90, 500, 'False');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (14, 'ODD', 0, 1.50, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (14, 'EVEN', 0, 2.05, 500, 'False');

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (15, 'SU_A', 0, 2.85, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (15, 'SU_H', 0, 1.25, 500, 'False');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (15, 'ATS_A', 1.5, 1.95, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (15, 'ATS_H', -1.5, 1.55, 500, 'False');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (15, 'SC_H', 6.5, 1.60, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (15, 'SC_L', 6.5, 1.90, 500, 'False');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (15, 'ODD', 0, 1.50, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (15, 'EVEN', 0, 2.05, 500, 'False');

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (16, 'SU_A', 0, 2.85, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (16, 'SU_H', 0, 1.25, 500, 'False');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (16, 'ATS_A', 1.5, 1.95, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (16, 'ATS_H', -1.5, 1.55, 500, 'False');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (16, 'SC_H', 6.5, 1.60, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (16, 'SC_L', 6.5, 1.90, 500, 'False');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (16, 'ODD', 0, 1.50, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (16, 'EVEN', 0, 2.05, 500, 'False');

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (17, 'SU_A', 0, 2.85, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (17, 'SU_H', 0, 1.25, 500, 'False');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (17, 'ATS_A', 1.5, 1.95, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (17, 'ATS_H', -1.5, 1.55, 500, 'False');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (17, 'SC_H', 6.5, 1.60, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (17, 'SC_L', 6.5, 1.90, 500, 'False');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (17, 'ODD', 0, 1.50, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (17, 'EVEN', 0, 2.05, 500, 'False');

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (18, 'SU_H', 0, 1.25, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (18, 'SU_A', 0, 2.15, 800, 'False');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (18, 'ATS_A', 1.5, 1.60, 900, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (18, 'ATS_H', -1.5, 1.90, 200, 'False');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (18, 'SC_H', 8.5, 1.70, 400, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (18, 'SC_L', 8.5, 1.80, 500, 'False');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (18, 'ODD', 0, 1.50, 600, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (18, 'EVEN', 0, 2.05, 700, 'False');

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (19, 'SU_A', 0, 2.15, 800, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (19, 'SU_H', 0, 1.45, 300, 'False');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (19, 'ATS_A', 1.5, 1.60, 200, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (19, 'ATS_H', -1.5, 1.90, 500, 'False');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (19, 'SC_H', 8.5, 1.70, 300, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (19, 'SC_L', 8.5, 1.80, 700, 'False');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (19, 'ODD', 0, 1.50, 600, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (19, 'EVEN', 0, 2.05, 400, 'False');

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (20, 'SU_H', 0, 1.70, 0, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (20, 'SU_A', 0, 1.25, 0, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (20, 'ATS_A', 1.5, 1.60, 0, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (20, 'ATS_H', -1.5, 1.90, 0, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (20, 'SC_H', 8.5, 1.70, 0, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (20, 'SC_L', 8.5, 1.80, 0, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (20, 'ODD', 0, 1.50, 0, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (20, 'EVEN', 0, 2.05, 0, null);

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (21, 'SU_H', 0, 1.70, 700, false);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (21, 'SU_A', 0, 1.25, 500, false);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (21, 'ATS_A', 1.5, 1.60, 400, false);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (21, 'ATS_H', -1.5, 1.90, 200, false);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (21, 'SC_H', 8.5, 1.70, 400, false);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (21, 'SC_L', 8.5, 1.80, 500, false);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (21, 'ODD', 0, 1.50, 600, false);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (21, 'EVEN', 0, 2.05, 700, false);

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (22, 'SU_H', 0, 1.85, 100, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (22, 'SU_A', 0, 1.65, 300, 'false');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (22, 'ATS_A', 1.5, 1.60, 400, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (22, 'ATS_H', -1.5, 1.90, 500, 'false');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (22, 'SC_H', 8.5, 1.70, 600, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (22, 'SC_L', 8.5, 1.80, 800, 'false');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (22, 'ODD', 0, 1.50, 200, 'TRUE');

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (22, 'EVEN', 0, 2.05, 400, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (23, 'SU_H', 0, 1.70, 500, 'false');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (23, 'SU_A', 0, 1.60, 600, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (23, 'ATS_A', 1.5, 1.60, 700, 'false');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (23, 'ATS_H', -1.5, 1.90, 900, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (23, 'SC_H', 8.5, 1.70, 300, 'false');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (23, 'SC_L', 8.5, 1.80, 600, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (23, 'ODD', 0, 1.50, 300, 'false');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (23, 'EVEN', 0, 2.05, 600, 'TRUE');

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (24, 'SU_H', 0, 1.20, 700, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (24, 'SU_A', 0, 2.10, 200, 'false');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (24, 'ATS_A', 1.5, 1.60, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (24, 'ATS_H', -1.5, 1.90, 300, 'false');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (24, 'SC_H', 8.5, 1.70, 100, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (24, 'SC_L', 8.5, 1.80, 800, 'false');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (24, 'ODD', 0, 1.50, 900, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (24, 'EVEN', 0, 2.05, 400, 'false');

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (25, 'SU_H', 0, 1.85, 300, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (25, 'SU_A', 0, 1.35, 200, 'false');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (25, 'ATS_A', 1.5, 1.60, 400, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (25, 'ATS_H', -1.5, 1.90, 500, 'false');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (25, 'SC_H', 8.5, 1.70, 600, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (25, 'SC_L', 8.5, 1.80, 300, 'false');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (25, 'ODD', 0, 1.50, 300, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (25, 'EVEN', 0, 2.05, 500, 'false');

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (26, 'SU_H', 0, 1.75, 400, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (26, 'SU_A', 0, 1.75, 600, 'false');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (26, 'ATS_A', 1.5, 1.60, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (26, 'ATS_H', -1.5, 1.90, 200, 'false');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (26, 'SC_H', 8.5, 1.70, 600, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (26, 'SC_L', 8.5, 1.80, 300, 'false');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (26, 'ODD', 0, 1.50, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (26, 'EVEN', 0, 2.05, 700, 'false');

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (27, 'SU_H', 0, 1.95, 300, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (27, 'SU_A', 0, 1.45, 100, 'false');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (27, 'ATS_A', 1.5, 1.60, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (27, 'ATS_H', -1.5, 1.90, 700, 'false');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (27, 'SC_H', 8.5, 1.70, 300, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (27, 'SC_L', 8.5, 1.80, 400, 'false');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (27, 'ODD', 0, 1.50, 600, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (27, 'EVEN', 0, 2.05, 700, 'false');

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (28, 'SU_H', 0, 1.25, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (28, 'SU_A', 0, 2.15, 800, 'false');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (28, 'ATS_A', 1.5, 1.60, 900, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (28, 'ATS_H', -1.5, 1.90, 200, 'false');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (28, 'SC_H', 8.5, 1.70, 400, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (28, 'SC_L', 8.5, 1.80, 500, 'false');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (28, 'ODD', 0, 1.50, 600, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (28, 'EVEN', 0, 2.05, 700, 'false');

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (29, 'SU_A', 0, 2.15, 800, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (29, 'SU_H', 0, 1.45, 300, 'false');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (29, 'ATS_A', 1.5, 1.60, 200, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (29, 'ATS_H', -1.5, 1.90, 500, 'false');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (29, 'SC_H', 8.5, 1.70, 300, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (29, 'SC_L', 8.5, 1.80, 700, 'false');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (29, 'ODD', 0, 1.50, 600, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (29, 'EVEN', 0, 2.05, 400, 'false');

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (30, 'SU_A', 0, 2.15, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (30, 'SU_H', 0, 1.45, 500, 'false');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (30, 'ATS_A', 1.5, 1.60, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (30, 'ATS_H', -1.5, 1.90, 500, 'false');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (30, 'SC_H', 7.5, 1.85, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (30, 'SC_L', 7.5, 1.65, 500, 'false');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (30, 'ODD', 0, 1.50, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (30, 'EVEN', 0, 2.05, 500, 'false');

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (31, 'SU_A', 0, 2.85, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (31, 'SU_H', 0, 1.25, 500, 'false');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (31, 'ATS_A', 1.5, 1.95, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (31, 'ATS_H', -1.5, 1.55, 500, 'false');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (31, 'SC_H', 6.5, 1.60, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (31, 'SC_L', 6.5, 1.90, 500, 'false');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (31, 'ODD', 0, 1.50, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (31, 'EVEN', 0, 2.05, 500, 'false');

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (32, 'SU_A', 0, 2.85, 100, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (32, 'SU_H', 0, 1.25, 220, 'false');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (32, 'ATS_A', 1.5, 1.95, 333, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (32, 'ATS_H', -1.5, 1.55, 400, 'false');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (32, 'SC_H', 6.5, 1.60, 560, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (32, 'SC_L', 6.5, 1.90, 607, 'false');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (32, 'ODD', 0, 1.50, 899, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (32, 'EVEN', 0, 2.05, 20, 'false');

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (33, 'SU_A', 0, 2.85, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (33, 'SU_H', 0, 1.25, 500, 'false');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (33, 'ATS_A', 1.5, 1.95, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (33, 'ATS_H', -1.5, 1.55, 500, 'false');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (33, 'SC_H', 6.5, 1.60, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (33, 'SC_L', 6.5, 1.90, 500, 'false');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (33, 'ODD', 0, 1.50, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (33, 'EVEN', 0, 2.05, 500, 'false');

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (34, 'SU_A', 0, 2.85, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (34, 'SU_H', 0, 1.25, 500, 'false');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (34, 'ATS_A', 1.5, 1.95, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (34, 'ATS_H', -1.5, 1.55, 500, 'false');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (34, 'SC_H', 6.5, 1.60, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (34, 'SC_L', 6.5, 1.90, 500, 'false');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (34, 'ODD', 0, 1.50, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (34, 'EVEN', 0, 2.05, 500, 'false');

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (35, 'SU_A', 0, 2.85, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (35, 'SU_H', 0, 1.25, 500, 'false');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (35, 'ATS_A', 1.5, 1.95, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (35, 'ATS_H', -1.5, 1.55, 500, 'false');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (35, 'SC_H', 6.5, 1.60, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (35, 'SC_L', 6.5, 1.90, 500, 'false');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (35, 'ODD', 0, 1.50, 500, 'TRUE');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (35, 'EVEN', 0, 2.05, 500, 'false');

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (36, 'SU_A', 0, 2.85, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (36, 'SU_H', 0, 1.25, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (36, 'ATS_A', 1.5, 1.95, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (36, 'ATS_H', -1.5, 1.55, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (36, 'SC_H', 6.5, 1.60, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (36, 'SC_L', 6.5, 1.90, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (36, 'ODD', 0, 1.50, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (36, 'EVEN', 0, 2.05, 500, null);

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (37, 'SU_A', 0, 2.85, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (37, 'SU_H', 0, 1.25, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (37, 'ATS_A', 1.5, 1.95, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (37, 'ATS_H', -1.5, 1.55, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (37, 'SC_H', 6.5, 1.60, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (37, 'SC_L', 6.5, 1.90, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (37, 'ODD', 0, 1.50, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (37, 'EVEN', 0, 2.05, 500, null);

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (38, 'SU_H', 0, 1.25, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (38, 'SU_A', 0, 2.15, 800, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (38, 'ATS_A', 1.5, 1.60, 900, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (38, 'ATS_H', -1.5, 1.90, 200, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (38, 'SC_H', 8.5, 1.70, 400, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (38, 'SC_L', 8.5, 1.80, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (38, 'ODD', 0, 1.50, 600, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (38, 'EVEN', 0, 2.05, 700, null);

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (39, 'SU_A', 0, 2.15, 800, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (39, 'SU_H', 0, 1.45, 300, 'true');
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (39, 'ATS_A', 1.5, 1.60, 200, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (39, 'ATS_H', -1.5, 1.90, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (39, 'SC_H', 8.5, 1.70, 300, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (39, 'SC_L', 8.5, 1.80, 700, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (39, 'ODD', 0, 1.50, 600, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (39, 'EVEN', 0, 2.05, 400, null);


insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (40, 'SU_H', 0, 1.70, 0, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (40, 'SU_A', 0, 1.25, 0, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (40, 'ATS_A', 1.5, 1.60, 0, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (40, 'ATS_H', -1.5, 1.90, 0, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (40, 'SC_H', 8.5, 1.70, 0, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (40, 'SC_L', 8.5, 1.80, 0, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (40, 'ODD', 0, 1.50, 0, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (40, 'EVEN', 0, 2.05, 0, null);


insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (41, 'SU_A', 0, 2.85, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (41, 'SU_H', 0, 1.25, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (41, 'ATS_A', 1.5, 1.95, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (41, 'ATS_H', -1.5, 1.55, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (41, 'SC_H', 6.5, 1.60, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (41, 'SC_L', 6.5, 1.90, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (41, 'ODD', 0, 1.50, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (41, 'EVEN', 0, 2.05, 500, null);

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (42, 'SU_A', 0, 2.85, 100, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (42, 'SU_H', 0, 1.25, 220, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (42, 'ATS_A', 1.5, 1.95, 333, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (42, 'ATS_H', -1.5, 1.55, 400, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (42, 'SC_H', 6.5, 1.60, 560, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (42, 'SC_L', 6.5, 1.90, 607, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (42, 'ODD', 0, 1.50, 899, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (42, 'EVEN', 0, 2.05, 20, null);

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (43, 'SU_A', 0, 2.85, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (43, 'SU_H', 0, 1.25, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (43, 'ATS_A', 1.5, 1.95, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (43, 'ATS_H', -1.5, 1.55, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (43, 'SC_H', 6.5, 1.60, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (43, 'SC_L', 6.5, 1.90, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (43, 'ODD', 0, 1.50, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (43, 'EVEN', 0, 2.05, 500, null);

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (44, 'SU_A', 0, 2.85, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (44, 'SU_H', 0, 1.25, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (44, 'ATS_A', 1.5, 1.95, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (44, 'ATS_H', -1.5, 1.55, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (44, 'SC_H', 6.5, 1.60, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (44, 'SC_L', 6.5, 1.90, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (44, 'ODD', 0, 1.50, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (44, 'EVEN', 0, 2.05, 500, null);

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (45, 'SU_A', 0, 2.85, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (45, 'SU_H', 0, 1.25, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (45, 'ATS_A', 1.5, 1.95, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (45, 'ATS_H', -1.5, 1.55, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (45, 'SC_H', 6.5, 1.60, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (45, 'SC_L', 6.5, 1.90, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (45, 'ODD', 0, 1.50, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (45, 'EVEN', 0, 2.05, 500, null);

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (46, 'SU_A', 0, 2.85, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (46, 'SU_H', 0, 1.25, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (46, 'ATS_A', 1.5, 1.95, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (46, 'ATS_H', -1.5, 1.55, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (46, 'SC_H', 6.5, 1.60, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (46, 'SC_L', 6.5, 1.90, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (46, 'ODD', 0, 1.50, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (46, 'EVEN', 0, 2.05, 500, null);

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (47, 'SU_A', 0, 2.85, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (47, 'SU_H', 0, 1.25, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (47, 'ATS_A', 1.5, 1.95, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (47, 'ATS_H', -1.5, 1.55, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (47, 'SC_H', 6.5, 1.60, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (47, 'SC_L', 6.5, 1.90, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (47, 'ODD', 0, 1.50, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (47, 'EVEN', 0, 2.05, 500, null);

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (48, 'SU_A', 0, 2.85, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (48, 'SU_H', 0, 1.25, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (48, 'ATS_A', 1.5, 1.95, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (48, 'ATS_H', -1.5, 1.55, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (48, 'SC_H', 6.5, 1.60, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (48, 'SC_L', 6.5, 1.90, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (48, 'ODD', 0, 1.50, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (48, 'EVEN', 0, 2.05, 500, null);

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (49, 'SU_A', 0, 2.85, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (49, 'SU_H', 0, 1.25, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (49, 'ATS_A', 1.5, 1.95, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (49, 'ATS_H', -1.5, 1.55, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (49, 'SC_H', 6.5, 1.60, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (49, 'SC_L', 6.5, 1.90, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (49, 'ODD', 0, 1.50, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (49, 'EVEN', 0, 2.05, 500, null);

insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (50, 'SU_A', 0, 2.85, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (50, 'SU_H', 0, 1.25, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (50, 'ATS_A', 1.5, 1.95, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (50, 'ATS_H', -1.5, 1.55, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (50, 'SC_H', 6.5, 1.60, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (50, 'SC_L', 6.5, 1.90, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (50, 'ODD', 0, 1.50, 500, null);
insert into ODDS (GAME_ID, ODD_TYPE, ODD_COMBINATION, ODD_VALUE, COUNT, IS_PASS) values (50, 'EVEN', 0, 2.05, 500, null);
*/

/*
insert into lottery (USER_ID, WIN, CAPITAL, CONFIRM_TIME, COMBINATION_COM1, COMBINATION_COM2, COMBINATION_COM3, COMBINATION_COM4, COMBINATION_COM5, COMBINATION_COM6, COMBINATION_COM7, COMBINATION_COM8, COMBINATION_COM0) values (1,-1,1000,'2014-08-08T10:50:20',1,null,null,null,null,null,null,null,null);
insert into lottery (USER_ID, WIN, CAPITAL, CONFIRM_TIME, COMBINATION_COM1, COMBINATION_COM2, COMBINATION_COM3, COMBINATION_COM4, COMBINATION_COM5, COMBINATION_COM6, COMBINATION_COM7, COMBINATION_COM8, COMBINATION_COM0) values (1,-1,1000,'2014-08-09T10:50:20',1,null,null,null,null,null,null,null,null);
insert into lottery (USER_ID, WIN, CAPITAL, CONFIRM_TIME, COMBINATION_COM1, COMBINATION_COM2, COMBINATION_COM3, COMBINATION_COM4, COMBINATION_COM5, COMBINATION_COM6, COMBINATION_COM7, COMBINATION_COM8, COMBINATION_COM0) values (1,-1,500,'2014-08-10T10:50:20',1,null,null,null,null,null,null,null,null);
insert into lottery (USER_ID, WIN, CAPITAL, CONFIRM_TIME, COMBINATION_COM1, COMBINATION_COM2, COMBINATION_COM3, COMBINATION_COM4, COMBINATION_COM5, COMBINATION_COM6, COMBINATION_COM7, COMBINATION_COM8, COMBINATION_COM0) values (2,-1,300,'2014-08-10T10:50:20',1,null,1,null,null,null,null,null,null);
insert into lottery (USER_ID, WIN, CAPITAL, CONFIRM_TIME, COMBINATION_COM1, COMBINATION_COM2, COMBINATION_COM3, COMBINATION_COM4, COMBINATION_COM5, COMBINATION_COM6, COMBINATION_COM7, COMBINATION_COM8, COMBINATION_COM0) values (2,-1,400,'2014-08-10T10:50:20',1,null,null,null,null,null,null,null,null);
insert into lottery (USER_ID, WIN, CAPITAL, CONFIRM_TIME, COMBINATION_COM1, COMBINATION_COM2, COMBINATION_COM3, COMBINATION_COM4, COMBINATION_COM5, COMBINATION_COM6, COMBINATION_COM7, COMBINATION_COM8, COMBINATION_COM0) values (2,-1,300,'2014-08-10T10:50:20',1,null,null,null,null,null,null,null,null);
insert into lottery (USER_ID, WIN, CAPITAL, CONFIRM_TIME, COMBINATION_COM1, COMBINATION_COM2, COMBINATION_COM3, COMBINATION_COM4, COMBINATION_COM5, COMBINATION_COM6, COMBINATION_COM7, COMBINATION_COM8, COMBINATION_COM0) values (2,-1,600,'2014-09-05T10:30:20',1,null,null,null,null,null,null,null,null);
insert into lottery (USER_ID, WIN, CAPITAL, CONFIRM_TIME, COMBINATION_COM1, COMBINATION_COM2, COMBINATION_COM3, COMBINATION_COM4, COMBINATION_COM5, COMBINATION_COM6, COMBINATION_COM7, COMBINATION_COM8, COMBINATION_COM0) values (1,-1,400,'2014-09-10T10:50:20',1,null,null,1,1,null,null,1,null);
insert into lottery (USER_ID, WIN, CAPITAL, CONFIRM_TIME, COMBINATION_COM1, COMBINATION_COM2, COMBINATION_COM3, COMBINATION_COM4, COMBINATION_COM5, COMBINATION_COM6, COMBINATION_COM7, COMBINATION_COM8, COMBINATION_COM0) values (2,-1,600,'2014-09-05T10:30:20',1,null,null,null,null,null,null,null,null);
insert into lottery (USER_ID, WIN, CAPITAL, CONFIRM_TIME, COMBINATION_COM1, COMBINATION_COM2, COMBINATION_COM3, COMBINATION_COM4, COMBINATION_COM5, COMBINATION_COM6, COMBINATION_COM7, COMBINATION_COM8, COMBINATION_COM0) values (2,-1,600,'2014-09-05T10:30:20',1,null,null,null,null,null,null,null,null);
insert into lottery (USER_ID, WIN, CAPITAL, CONFIRM_TIME, COMBINATION_COM1, COMBINATION_COM2, COMBINATION_COM3, COMBINATION_COM4, COMBINATION_COM5, COMBINATION_COM6, COMBINATION_COM7, COMBINATION_COM8, COMBINATION_COM0) values (2,-1,600,'2014-09-05T10:30:20',1,null,null,null,null,null,null,null,null);
insert into lottery (USER_ID, WIN, CAPITAL, CONFIRM_TIME, COMBINATION_COM1, COMBINATION_COM2, COMBINATION_COM3, COMBINATION_COM4, COMBINATION_COM5, COMBINATION_COM6, COMBINATION_COM7, COMBINATION_COM8, COMBINATION_COM0) values (2,-1,600,'2014-09-05T10:30:20',1,null,null,null,null,null,null,null,null);
*/

/*
insert into lottery_odds (lottery_id, odds_id) values (4, 361);
insert into lottery_odds (lottery_id, odds_id) values (4, 363);
insert into lottery_odds (lottery_id, odds_id) values (4, 365);
insert into lottery_odds (lottery_id, odds_id) values (5, 362);
insert into lottery_odds (lottery_id, odds_id) values (5, 364);
insert into lottery_odds (lottery_id, odds_id) values (5, 366);
insert into lottery_odds (lottery_id, odds_id) values (5, 368);
insert into lottery_odds (lottery_id, odds_id) values (6, 362);
insert into lottery_odds (lottery_id, odds_id) values (7, 306);
insert into lottery_odds (lottery_id, odds_id) values (8, 305);
insert into lottery_odds (lottery_id, odds_id) values (8, 316);
insert into lottery_odds (lottery_id, odds_id) values (9, 318);
insert into lottery_odds (lottery_id, odds_id) values (9, 320);
insert into lottery_odds (lottery_id, odds_id) values (10, 314);
insert into lottery_odds (lottery_id, odds_id) values (10, 317);
insert into lottery_odds (lottery_id, odds_id) values (10, 320);
insert into lottery_odds (lottery_id, odds_id) values (11, 311);
insert into lottery_odds (lottery_id, odds_id) values (11, 319);
insert into lottery_odds (lottery_id, odds_id) values (12, 311);
insert into lottery_odds (lottery_id, odds_id) values (12, 300);
insert into lottery_odds (lottery_id, odds_id) values (12, 256);
insert into lottery_odds (lottery_id, odds_id) values (12, 240);
insert into lottery_odds (lottery_id, odds_id) values (12, 224);
*/
